// Code generated by MockGen. DO NOT EDIT.
// Source: application/usecase/thread/time_getter.go
//
// Generated by this command:
//
//	mockgen -source=application/usecase/thread/time_getter.go -destination=application/mock/thread/mock_time_getter.go -package=mock_thread
//

// Package mock_thread is a generated GoMock package.
package mock_thread

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockITimeGetter is a mock of ITimeGetter interface.
type MockITimeGetter struct {
	ctrl     *gomock.Controller
	recorder *MockITimeGetterMockRecorder
	isgomock struct{}
}

// MockITimeGetterMockRecorder is the mock recorder for MockITimeGetter.
type MockITimeGetterMockRecorder struct {
	mock *MockITimeGetter
}

// NewMockITimeGetter creates a new mock instance.
func NewMockITimeGetter(ctrl *gomock.Controller) *MockITimeGetter {
	mock := &MockITimeGetter{ctrl: ctrl}
	mock.recorder = &MockITimeGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITimeGetter) EXPECT() *MockITimeGetterMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockITimeGetter) Now(ctx context.Context) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now", ctx)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockITimeGetterMockRecorder) Now(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockITimeGetter)(nil).Now), ctx)
}
