// Code generated by MockGen. DO NOT EDIT.
// Source: handler/thread/handler.go
//
// Generated by this command:
//
//	mockgen -source=handler/thread/handler.go -destination=handler/thread/mock_thread/mock_handler.go -package=mock_thread
//

// Package mock_thread is a generated GoMock package.
package mock_thread

import (
	context "context"
	reflect "reflect"

	thread "github.com/nakanokota/bulletin-board-system/backend/application/usecase/thread"
	gomock "go.uber.org/mock/gomock"
)

// MocklistThreadsUsecase is a mock of listThreadsUsecase interface.
type MocklistThreadsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MocklistThreadsUsecaseMockRecorder
	isgomock struct{}
}

// MocklistThreadsUsecaseMockRecorder is the mock recorder for MocklistThreadsUsecase.
type MocklistThreadsUsecaseMockRecorder struct {
	mock *MocklistThreadsUsecase
}

// NewMocklistThreadsUsecase creates a new mock instance.
func NewMocklistThreadsUsecase(ctrl *gomock.Controller) *MocklistThreadsUsecase {
	mock := &MocklistThreadsUsecase{ctrl: ctrl}
	mock.recorder = &MocklistThreadsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistThreadsUsecase) EXPECT() *MocklistThreadsUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MocklistThreadsUsecase) Exec(ctx context.Context, cmd thread.ListThreadsCommand) (*thread.ListThreadsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, cmd)
	ret0, _ := ret[0].(*thread.ListThreadsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MocklistThreadsUsecaseMockRecorder) Exec(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MocklistThreadsUsecase)(nil).Exec), ctx, cmd)
}
