// Code generated by MockGen. DO NOT EDIT.
// Source: handler/thread/create_thread_handler.go
//
// Generated by this command:
//
//	mockgen -source=handler/thread/create_thread_handler.go -destination=handler/thread/mock_thread/mock_create_thread_handler.go -package=mock_thread
//

// Package mock_thread is a generated GoMock package.
package mock_thread

import (
	context "context"
	reflect "reflect"

	thread "github.com/nakanokota/bulletin-board-system/backend/application/usecase/thread"
	gomock "go.uber.org/mock/gomock"
)

// MockcreateThreadUsecase is a mock of createThreadUsecase interface.
type MockcreateThreadUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockcreateThreadUsecaseMockRecorder
	isgomock struct{}
}

// MockcreateThreadUsecaseMockRecorder is the mock recorder for MockcreateThreadUsecase.
type MockcreateThreadUsecaseMockRecorder struct {
	mock *MockcreateThreadUsecase
}

// NewMockcreateThreadUsecase creates a new mock instance.
func NewMockcreateThreadUsecase(ctrl *gomock.Controller) *MockcreateThreadUsecase {
	mock := &MockcreateThreadUsecase{ctrl: ctrl}
	mock.recorder = &MockcreateThreadUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateThreadUsecase) EXPECT() *MockcreateThreadUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockcreateThreadUsecase) Exec(ctx context.Context, cmd thread.CreateThreadCommand) (*thread.CreateThreadOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, cmd)
	ret0, _ := ret[0].(*thread.CreateThreadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockcreateThreadUsecaseMockRecorder) Exec(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockcreateThreadUsecase)(nil).Exec), ctx, cmd)
}
