// Code generated by MockGen. DO NOT EDIT.
// Source: domain/thread/repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/thread/repository.go -destination=domain/thread/mock_thread/mock_repository.go -package=mock_thread
//

// Package mock_thread is a generated GoMock package.
package mock_thread

import (
	context "context"
	reflect "reflect"

	thread "github.com/nakanokota/bulletin-board-system/backend/domain/thread"
	gomock "go.uber.org/mock/gomock"
)

// MockIThreadFetcher is a mock of IThreadFetcher interface.
type MockIThreadFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockIThreadFetcherMockRecorder
	isgomock struct{}
}

// MockIThreadFetcherMockRecorder is the mock recorder for MockIThreadFetcher.
type MockIThreadFetcherMockRecorder struct {
	mock *MockIThreadFetcher
}

// NewMockIThreadFetcher creates a new mock instance.
func NewMockIThreadFetcher(ctrl *gomock.Controller) *MockIThreadFetcher {
	mock := &MockIThreadFetcher{ctrl: ctrl}
	mock.recorder = &MockIThreadFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIThreadFetcher) EXPECT() *MockIThreadFetcherMockRecorder {
	return m.recorder
}

// FetchActiveThreadListNewestFirst mocks base method.
func (m *MockIThreadFetcher) FetchActiveThreadListNewestFirst(ctx context.Context) (*thread.ThreadList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchActiveThreadListNewestFirst", ctx)
	ret0, _ := ret[0].(*thread.ThreadList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchActiveThreadListNewestFirst indicates an expected call of FetchActiveThreadListNewestFirst.
func (mr *MockIThreadFetcherMockRecorder) FetchActiveThreadListNewestFirst(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchActiveThreadListNewestFirst", reflect.TypeOf((*MockIThreadFetcher)(nil).FetchActiveThreadListNewestFirst), ctx)
}

// MockIPendingThreadRepository is a mock of IPendingThreadRepository interface.
type MockIPendingThreadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPendingThreadRepositoryMockRecorder
	isgomock struct{}
}

// MockIPendingThreadRepositoryMockRecorder is the mock recorder for MockIPendingThreadRepository.
type MockIPendingThreadRepositoryMockRecorder struct {
	mock *MockIPendingThreadRepository
}

// NewMockIPendingThreadRepository creates a new mock instance.
func NewMockIPendingThreadRepository(ctrl *gomock.Controller) *MockIPendingThreadRepository {
	mock := &MockIPendingThreadRepository{ctrl: ctrl}
	mock.recorder = &MockIPendingThreadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPendingThreadRepository) EXPECT() *MockIPendingThreadRepositoryMockRecorder {
	return m.recorder
}

// CreateThread mocks base method.
func (m *MockIPendingThreadRepository) CreateThread(ctx context.Context, pendingThread *thread.PendingThread) (*thread.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThread", ctx, pendingThread)
	ret0, _ := ret[0].(*thread.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThread indicates an expected call of CreateThread.
func (mr *MockIPendingThreadRepositoryMockRecorder) CreateThread(ctx, pendingThread any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThread", reflect.TypeOf((*MockIPendingThreadRepository)(nil).CreateThread), ctx, pendingThread)
}

// MockIThreadFileChecker is a mock of IThreadFileChecker interface.
type MockIThreadFileChecker struct {
	ctrl     *gomock.Controller
	recorder *MockIThreadFileCheckerMockRecorder
	isgomock struct{}
}

// MockIThreadFileCheckerMockRecorder is the mock recorder for MockIThreadFileChecker.
type MockIThreadFileCheckerMockRecorder struct {
	mock *MockIThreadFileChecker
}

// NewMockIThreadFileChecker creates a new mock instance.
func NewMockIThreadFileChecker(ctrl *gomock.Controller) *MockIThreadFileChecker {
	mock := &MockIThreadFileChecker{ctrl: ctrl}
	mock.recorder = &MockIThreadFileCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIThreadFileChecker) EXPECT() *MockIThreadFileCheckerMockRecorder {
	return m.recorder
}

// ExistsFile mocks base method.
func (m *MockIThreadFileChecker) ExistsFile(ctx context.Context, fileID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsFile", ctx, fileID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsFile indicates an expected call of ExistsFile.
func (mr *MockIThreadFileCheckerMockRecorder) ExistsFile(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsFile", reflect.TypeOf((*MockIThreadFileChecker)(nil).ExistsFile), ctx, fileID)
}

// IsFileAttachedToThread mocks base method.
func (m *MockIThreadFileChecker) IsFileAttachedToThread(ctx context.Context, fileID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFileAttachedToThread", ctx, fileID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFileAttachedToThread indicates an expected call of IsFileAttachedToThread.
func (mr *MockIThreadFileCheckerMockRecorder) IsFileAttachedToThread(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFileAttachedToThread", reflect.TypeOf((*MockIThreadFileChecker)(nil).IsFileAttachedToThread), ctx, fileID)
}
