// Code generated by MockGen. DO NOT EDIT.
// Source: domain/thread/repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/thread/repository.go -destination=application/thread/mock_thread/mock_repository.go -package=mock_thread
//

// Package mock_thread is a generated GoMock package.
package mock_thread

import (
	context "context"
	reflect "reflect"

	thread "github.com/nakanokota/bulletin-board-system/backend/domain/thread"
	gomock "go.uber.org/mock/gomock"
)

// MockIThreadRepository is a mock of IThreadRepository interface.
type MockIThreadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIThreadRepositoryMockRecorder
	isgomock struct{}
}

// MockIThreadRepositoryMockRecorder is the mock recorder for MockIThreadRepository.
type MockIThreadRepositoryMockRecorder struct {
	mock *MockIThreadRepository
}

// NewMockIThreadRepository creates a new mock instance.
func NewMockIThreadRepository(ctrl *gomock.Controller) *MockIThreadRepository {
	mock := &MockIThreadRepository{ctrl: ctrl}
	mock.recorder = &MockIThreadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIThreadRepository) EXPECT() *MockIThreadRepositoryMockRecorder {
	return m.recorder
}

// FetchActiveThreadList mocks base method.
func (m *MockIThreadRepository) FetchActiveThreadList(ctx context.Context) (*thread.ThreadList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchActiveThreadList", ctx)
	ret0, _ := ret[0].(*thread.ThreadList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchActiveThreadList indicates an expected call of FetchActiveThreadList.
func (mr *MockIThreadRepositoryMockRecorder) FetchActiveThreadList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchActiveThreadList", reflect.TypeOf((*MockIThreadRepository)(nil).FetchActiveThreadList), ctx)
}
