// Code generated by MockGen. DO NOT EDIT.
// Source: application/thread/query_service.go
//
// Generated by this command:
//
//	mockgen -source=application/thread/query_service.go -destination=application/thread/mock_thread/mock_query_service.go -package=mock_thread
//

// Package mock_thread is a generated GoMock package.
package mock_thread

import (
	context "context"
	reflect "reflect"

	thread "github.com/nakanokota/bulletin-board-system/backend/application/thread"
	gomock "go.uber.org/mock/gomock"
)

// MockIThreadQueryService is a mock of IThreadQueryService interface.
type MockIThreadQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockIThreadQueryServiceMockRecorder
	isgomock struct{}
}

// MockIThreadQueryServiceMockRecorder is the mock recorder for MockIThreadQueryService.
type MockIThreadQueryServiceMockRecorder struct {
	mock *MockIThreadQueryService
}

// NewMockIThreadQueryService creates a new mock instance.
func NewMockIThreadQueryService(ctrl *gomock.Controller) *MockIThreadQueryService {
	mock := &MockIThreadQueryService{ctrl: ctrl}
	mock.recorder = &MockIThreadQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIThreadQueryService) EXPECT() *MockIThreadQueryServiceMockRecorder {
	return m.recorder
}

// FetchThreadList mocks base method.
func (m *MockIThreadQueryService) FetchThreadList(ctx context.Context) ([]thread.ThreadListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchThreadList", ctx)
	ret0, _ := ret[0].([]thread.ThreadListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchThreadList indicates an expected call of FetchThreadList.
func (mr *MockIThreadQueryServiceMockRecorder) FetchThreadList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchThreadList", reflect.TypeOf((*MockIThreadQueryService)(nil).FetchThreadList), ctx)
}
